[package]
name = "jwerle/varint-wasm"
version = "0.1.0"
description = "A varint implementation written in ZZ compiled to WASM"
license = "MIT"
repository = "little-core-labs/varint-wasm"
readme = "README.md"
homepage = "https://github.com/little-core-labs/varint-wasm"

[[module]]
name = "varint"
source = "varint.wasm"
